[build]
  command = "make build/aws"
  functions = "functions"
  publish = "site"
[build.environment]
  # Change this path with the path to your repository
  GO_IMPORT_PATH = "https://github.com/DevsQuotes/DevsQuotesPrinter"
